- name: solana folder
  file:
    path: /solana
    state: directory
    owner: solana
    group: solana
    mode: "0777"
  become: true
  become_user: root

- name: solana snapshots
  file:
    path: /solana/ledger
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana ledger
  file:
    path: /solana/ledger
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana accounts
  file:
    path: /solana/accounts
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana logs
  become: true
  become_user: root
  file:
    path: /solana/logs
    state: directory
    owner: solana
    group: solana

