- name: create solana validator logrotate
  become: true
  become_user: root
  file:
    path: /etc/logrotate.d/solana-validator
    state: touch
    mode: "0644"
    owner: root
    group: root
    modification_time: preserve
    access_time: preserve

- name: logrotate for solana-validator.log
  become: true
  become_user: root
  blockinfile:
    path: /etc/logrotate.d/solana-validator
    block: |
      /solana/logs/solana-validator.log {
        rotate 7
        daily
        missingok
        postrotate
          systemctl kill -s USR1 solana-validator.service
        endscript
      }
