- name: Create swap file
  become: true
  become_user: root
  command:
    dd if=/dev/zero of=/solana/accounts/swap bs=1024 count={{ swap_mb }}k
    creates="/solana/accounts/swap"

- name: Change swap file permissions
  become: true
  become_user: root
  file: 
    path=/solana/accounts/swap
    owner=root
    group=root
    mode=0600

- name: Check swap file type
  become: true
  become_user: root
  command: file /solana/accounts/swap
  register: swap

- name: Make swap file
  become: true
  become_user: root
  command: "sudo mkswap /solana/accounts/swap"
  when: swap.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  become: true
  become_user: root
  mount: name=none
    src=/solana/accounts/swap
    fstype=swap
    opts=sw
    passno=0
    dump=0
    state=present

- name: swap check
  become: true
  become_user: root
  ignore_errors: yes
  shell: swapon -show | grep /solana/accounts/swap
  register: swap_check

- name: Mount swap
  become: true
  become_user: root
  command: "swapon /solana/accounts/swap"
  when: swap_check.rc != 0
